x-environment:
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_dk_project_postgis'
    container_name: prge_dk_project_postgis-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgis-remote-data:/var/lib/postgresql/data


  geoserver:
    build:
      context: ..
      dockerfile: docker/geoserver/Dockerfile
    image: 'prge_dk_project_geoserver'
    container_name: prge_dk_project_geoserver-${ENV_NAME}
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver-data
      - GEOSERVER_CSRF_WHITELIST=localhost
    ports:
      - ${GEOSERVER_PORT}:8080
    volumes:
      - geoserver-data:/opt/geoserver-data



  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    image: 'prge_dk_project_fastapi'
    container_name: prge_dk_project_fastapi-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${FASTAPI_PORT}:10000


  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
      args:
        NGINX_PORT: ${NGINX_PORT}
    image: 'prge_dk_project_nginx'
    container_name: prge_dk_project_nginx-${ENV_NAME}
    ports:
      - ${NGINX_PORT}:80


volumes:
  geoserver-data:
  postgis-remote-data:
